/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import connection.DBConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose
 */
public class FormTicketsUpdate extends javax.swing.JFrame {

    String id_ticket;
    Statement statement = null;
    ResultSet resultSet = null;
    ResultSet resultTipus = null;

    /**
     * Creates new form FormTicketsUpdate
     *
     * @param id_seleccionat
     */
    public FormTicketsUpdate(String id_seleccionat) {
        //this.setExtendedState(this.MAXIMIZED_BOTH);
        initComponents();
        loadcombo();
        id_ticket = id_seleccionat;
        String dades_ticket_sql = "select p.id, tp.nom, tp.id as id_tipus, p.descripcio, ap.data_entrada, ap.mida, ap.tickets_viatges, ap.preu, p.estat from productes p left join atributs_producte ap on p.atributs = ap.id left join tipus_producte tp on ap.nom = tp.id where p.id = " + id_ticket;
        System.out.println("id_seleccionat update: " + id_seleccionat);
        System.out.println(dades_ticket_sql);
        try {
            statement = DBConnection.getConnection().createStatement();
            resultSet = statement.executeQuery(dades_ticket_sql);
            resultSet.first();
            selectTipus.setSelectedItem(resultSet.getString("nom"));
            preu.setValue(resultSet.getInt("preu"));
            numViatges.setValue(resultSet.getInt("tickets_viatges"));
            if (resultSet.getString("data_entrada") != null) {
                dataEntrada.setText(resultSet.getString("data_entrada"));
            } else {
                dataEntrada.setVisible(false);
                jLabel6.setVisible(false);
            }

            if (resultSet.getBoolean("estat")) {
                selectEstat.setSelectedItem("Actiu");
            } else {
                selectEstat.setSelectedItem("Desactivat");
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, e);
        } finally {
            try {
                statement.close();
                DBConnection.disconnect();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(this, e);
            }
        }

    }

    private FormTicketsUpdate() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        selectTipus = new javax.swing.JComboBox<>();
        selectEstat = new javax.swing.JComboBox<>();
        numViatges = new javax.swing.JSpinner();
        preu = new javax.swing.JSpinner();
        guardarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        dataEntrada = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Modificat ticket");

        jLabel2.setText("Número de viatges");

        jLabel3.setText("Tipus");

        jLabel4.setText("Preu (€)");

        jLabel5.setText("Estat");

        selectTipus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        selectEstat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Actiu", "Desactivat"}));

        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Data entrada:");

        dataEntrada.setText("null");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(173, 173, 173))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(guardarButton)
                    .addComponent(jLabel6))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarButton)
                    .addComponent(selectTipus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectEstat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numViatges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(preu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(selectTipus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numViatges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(preu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(selectEstat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton)
                    .addComponent(guardarButton))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        FormTickets ft = new FormTickets();
        this.setVisible(false);
        ft.setVisible(true);
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        // TODO add your handling code here:
        try {
            String data_entrada;
            String update_atributs_ticket_query = "";
            int tipus = selectTipus.getSelectedIndex() + 1;
            int nViatges = (Integer) numViatges.getValue();
            int valorPreu = (Integer) preu.getValue();
            if (dataEntrada.getText().equalsIgnoreCase(null)) {
                data_entrada = "'" + dataEntrada.getText() + "'";
                update_atributs_ticket_query = "update atributs_producte set nom = " + tipus + ", tickets_viatges = " + nViatges + ", preu = " + valorPreu + ", data_entrada = " + data_entrada + " where id = " + id_ticket + ";";

            } else {
                update_atributs_ticket_query = "update atributs_producte set nom = " + tipus + ", tickets_viatges = " + nViatges + ", preu = " + valorPreu + " where id = " + id_ticket + ";";
            }
            int estat_ticket;
            String estat_ticket_selector = (String) selectEstat.getSelectedItem();
            if (estat_ticket_selector.equalsIgnoreCase("Actiu")) {
                estat_ticket = 1;
            } else {
                estat_ticket = 0;
            }
            String update_ticket_query = "update productes set Estat = " + estat_ticket + " where id = " + id_ticket + ";";
            System.out.println(update_atributs_ticket_query);
            System.out.println(update_ticket_query);
            statement = DBConnection.getConnection().createStatement();
            statement.executeUpdate(update_atributs_ticket_query);
            statement.executeUpdate(update_ticket_query);
            JOptionPane.showMessageDialog(this, "Ticket actualitzat correctament");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, e);
        } finally {
            try {
                statement.close();
                DBConnection.disconnect();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(this, e);
            }
            FormTickets ft = new FormTickets();
            this.setVisible(false);
            ft.setVisible(true);
        }

    }//GEN-LAST:event_guardarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTicketsUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTicketsUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTicketsUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTicketsUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTicketsUpdate().setVisible(true);
            }
        });
    }

    void loadcombo() {
        try {
            statement = DBConnection.getConnection().createStatement();
            resultTipus = statement.executeQuery("select nom from tipus_producte where id in (1,2,3,4,5,6,7);");
            while (resultTipus.next()) {
                selectTipus.addItem(resultTipus.getString(1));
            }
            DBConnection.disconnect();
        } catch (Exception e) {
            System.out.println("Error" + e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField dataEntrada;
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner numViatges;
    private javax.swing.JSpinner preu;
    private javax.swing.JComboBox<String> selectEstat;
    private javax.swing.JComboBox<String> selectTipus;
    // End of variables declaration//GEN-END:variables
}
